.Dd Aug 9, 2020
.Dt lts 5
.Os
.Sh NAME
.Nm lts
.Nd file time data
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
set of utilities print file time data to standard output
similar to
.Xr stat 1 .
They have been broken down due to portability considerations.
For a full explanation of the utilities, please see the relevant manual
page.
.Sh SEE ALSO
.Xr lat 1
.Xr lmt 1
.Xr lct 1
.Xr stat 1
